# Generated by Django 4.2.7 on 2024-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_contactimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='header_images/')),
            ],
        ),
    ]
