# Generated by Django 4.2.7 on 2024-06-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_calltoaction_p_a_headerimage_teammember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallToAction',
            new_name='PropertyAgent_CallToAction',
        ),
        migrations.RenameModel(
            old_name='P_A_HeaderImage',
            new_name='PropertyAgent_HeaderImage',
        ),
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='PropertyAgent_TeamMember',
        ),
    ]
