# Generated by Django 4.2.7 on 2024-06-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_aboutus_calltoaction_aboutus_headerimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cta_images')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Home_HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='header_images')),
            ],
        ),
        migrations.CreateModel(
            name='Home_Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_designation', models.CharField(max_length=255)),
                ('author_image', models.ImageField(upload_to='testimonial_images')),
            ],
        ),
        migrations.CreateModel(
            name='Home_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('carousel_images', models.ManyToManyField(to='properties.home_headerimage')),
            ],
        ),
    ]
