# Generated by Django 4.2.7 on 2024-06-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_home_calltoaction_home_headerimage_home_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_testimonial',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
