# Generated by Django 4.2.7 on 2024-07-02 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_home_testimonial_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='header_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('cv', models.FileField(upload_to='cvs/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
