# Generated by Django 4.2.7 on 2024-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_career_headerimage_careerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sell', 'For Sell'), ('sold', 'Sold'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='sell', max_length=10),
        ),
    ]
