# Generated by Django 4.2.7 on 2024-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('P', 'Primary Project'), ('S', 'Secondary Project'), ('L', 'Land Shearing'), ('J', 'Joint Venture')], default='J', max_length=2),
        ),
    ]
