# Generated by Django 4.2.7 on 2024-08-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_belcony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
    ]
