# Generated by Django 4.2.7 on 2024-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_property_image_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='drawingroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='dyningroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('On Going', 'On Going'), ('Pending', 'Pending')], default='Completed', max_length=10),
        ),
    ]
