# Generated by Django 4.2.7 on 2024-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_drawingroom_property_dyningroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sell', 'For Sell'), ('sold', 'Sold'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('On Going', 'On Going')], default='sell', max_length=10),
        ),
    ]
