# Generated by Django 4.2.7 on 2024-08-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_property_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
    ]
