# Generated by Django 4.2.7 on 2024-08-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_remove_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sell', 'For Sell'), ('sold', 'Sold'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('on_going', 'On Going')], default='sell', max_length=10),
        ),
    ]
