# Generated by Django 4.2.7 on 2024-08-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sell', 'For Sell'), ('sold', 'Sold'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('ongoing', 'OnGoing')], default='sell', max_length=10),
        ),
    ]
