# Generated by Django 4.2.7 on 2024-09-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_department_careerapplication_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Career_Department',
        ),
    ]
