# Generated by Django 4.2.7 on 2024-10-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_rename_department_career_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='portfolios/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
